### ISSUE TITLE
meta: refactor

### ISSUE THREAD

**Issue by BastiHz** [BastiHz/epicycles#25]
- [x] Better file structure, put all R stuff in subfolder, create src folder, call the main file in the top directory "epicycles.py".
- [x] Improve readme #15 
- [x] Change how drawing works, no more transparency, line points as a fifo queue. #21 and #18.
- [x] Create a state machine to make later changes easier
- [x] Create a debug overlay showing fps, angle in rad and degrees, angular velocity in rad/s and °/s. Remove the print output.

**Comment by BastiHz** [comment]
on PC, hilbert curve, 900*900 display, max speed
without fading: ~3100 points
with fading: ~ 4000 points
Why? And why does it not change immediately after pressing F?
